'use strict';
const $=s=>document.querySelector(s), D=E0Domain;
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n/100);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today='2026-09-23'; let counter=50;
function initial(){return {mode:'admin',view:'summary',online:true,branch:'Todas',period:'today',cart:[],session:null,closures:[],
 products:[
 {id:'p1',name:'Anillo espiral',type:'Anillos',material:'Plata',code:'010100240000015',price:100000,cost:50000,available:8,reserved:1,damaged:0},
 {id:'p2',name:'Aretes luna',type:'Aretes',material:'Plata',code:'010200320000016',price:78000,cost:34000,available:12,reserved:0,damaged:1},
 {id:'p3',name:'Dije corazón',type:'Dijes',material:'Plata',code:'010300210000017',price:65000,cost:28000,available:3,reserved:1,damaged:0},
 {id:'p4',name:'Pulsera eslabón',type:'Pulseras',material:'Plata',code:'010400640000018',price:150000,cost:72000,available:5,reserved:1,damaged:0},
 {id:'p5',name:'Collar nudo',type:'Collares',material:'Tumbaga',code:'030500000000019',price:90000,cost:42000,available:1,reserved:0,damaged:0},
 {id:'p6',name:'Anillo sol',type:'Anillos',material:'Oro',code:'020100280000020',price:275000,cost:160000,available:4,reserved:0,damaged:0}],
 clients:[{id:'c1',name:'Cliente de ejemplo 01',phone:'55 0000 0101',credit:10000},{id:'c2',name:'Cliente de ejemplo 02',phone:'55 0000 0102',credit:0}],
 orders:[{id:'AP-001',kind:'layaway',client:'c1',items:['p1'],description:'Anillo espiral',total:100000,cost:50000,paid:40000,status:'Pendiente',delivered:false,branch:'Sucursal 1',seller:'Emma',date:'2026-09-20',due:'2026-11-04',history:['20/09 · Alta y anticipo $400.00']},
 {id:'AP-002',kind:'layaway',client:'c2',items:['p4'],description:'Pulsera eslabón',total:150000,cost:72000,paid:150000,status:'Liquidada',delivered:false,branch:'Sucursal 2',seller:'Lucía',date:'2026-09-10',due:'2026-10-25',history:['10/09 · Alta y anticipo $600.00','23/09 · Liquidación $900.00']},
 {id:'RP-001',kind:'repair',client:'c1',items:[],description:'Cadena del cliente · reparar broche',total:100000,cost:0,paid:50000,status:'Recibida',started:false,delivered:false,branch:'Sucursal 1',seller:'Matanga',date:today,due:'Al pasar a lista',history:['23/09 · Recepción y anticipo $500.00']},
 {id:'RP-002',kind:'repair',client:'c2',items:[],description:'Anillo del cliente · ajuste',total:80000,cost:0,paid:80000,status:'Lista para entregar',started:true,delivered:false,branch:'Sucursal 2',seller:'Matanga',date:'2026-09-18',due:'2026-11-05',history:['18/09 · Recepción','21/09 · En reparación','21/09 · Liquidación','21/09 · Lista para entregar']}],
 entries:[
 {id:'V-101',date:today,hour:'10:15',branch:'Sucursal 1',type:'Venta',description:'Anillo espiral',gross:100000,discount:0,cost:50000,cash:40000,card:60000,transfer:0,seller:'Emma',net:100000},
 {id:'V-102',date:today,hour:'11:20',branch:'Sucursal 2',type:'Venta',description:'Aretes luna',gross:78000,discount:0,cost:34000,cash:78000,card:0,transfer:0,seller:'Lucía',net:78000},
 {id:'A-103',date:today,hour:'12:10',branch:'Sucursal 2',type:'Liquidación apartado',description:'AP-002 · Pulsera eslabón',gross:150000,discount:0,cost:72000,cash:90000,card:0,transfer:0,seller:'Lucía',net:150000},
 {id:'R-104',date:today,hour:'13:10',branch:'Sucursal 1',type:'Anticipo reparación',description:'RP-001 · Cadena del cliente',gross:0,discount:0,cost:0,cash:50000,card:0,transfer:0,seller:'Matanga',net:0},
 {id:'V-105',date:today,hour:'15:05',branch:'Sucursal 1',type:'Venta',description:'Dije corazón',gross:65000,discount:0,cost:28000,cash:0,card:65000,transfer:0,seller:'Emma',net:65000},
 {id:'V-106',date:'2026-09-22',hour:'16:30',branch:'Sucursal 2',type:'Venta',description:'Anillo sol',gross:275000,discount:0,cost:160000,cash:0,card:275000,transfer:0,seller:'Lucía',net:275000}],reviewed:[]};}
let state=initial();
const names={summary:'Resumen del negocio',sale:'Nueva venta',receipts:'Ventas y comprobantes',cash:'Caja',inventory:'Inventario',layaway:'Apartados',repair:'Reparaciones',clients:'Clientes y saldo',sellers:'Vendedores',alerts:'Alertas',corrections:'Correcciones',settings:'Configuración'};
function badge(s,w=false){return `<span class="badge${w?' warning':''}">${esc(s)}</span>`;}
function notice(t){return `<div class="notice">${t}</div>`;}
function title(t,sub=''){return `<div class="eyebrow">${state.mode==='admin'?'Administración':'Punto de venta · Sucursal 1'}</div><h1>${t}</h1><p class="subtitle">${sub}</p>`;}
function button(action,label,extra='',cls=''){return `<button type="button" data-action="${action}" ${extra} class="${cls}">${label}</button>`;}
function client(id){return state.clients.find(x=>x.id===id)?.name||'Cliente de ejemplo';}
function rows(){return state.entries.filter(e=>(state.branch==='Todas'||e.branch===state.branch)&&(state.period==='all'||e.date===(state.period==='today'?today:'2026-09-22')));}
function filters(){return `<div class="toolbar"><label>Período<select id="period"><option value="today" ${state.period==='today'?'selected':''}>Hoy · 23 sep 2026</option><option value="yesterday" ${state.period==='yesterday'?'selected':''}>Ayer · 22 sep 2026</option><option value="all" ${state.period==='all'?'selected':''}>Todo el ejemplo</option></select></label><label>Sucursal<select id="branch">${['Todas','Sucursal 1','Sucursal 2'].map(b=>`<option ${b===state.branch?'selected':''}>${b}</option>`).join('')}</select></label><small>Datos ficticios de las fechas indicadas</small></div>`;}
function entryTable(entries){return `<div class="table-wrap"><table><thead><tr><th>Comprobante</th><th>Operación</th><th>Sucursal</th><th class="numeric">Venta neta</th><th class="numeric">Cobro recibido</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${button('receipt',esc(e.id),`data-id="${e.id}"`,'link')}<br><small>${e.date.slice(8)} sep · ${e.hour}</small></td><td>${esc(e.type)}<br><small>${esc(e.description)}</small></td><td>${e.branch}<br><small>${e.pending?'Pendiente de envío (demo)':e.seller}</small></td><td class="numeric">${money(e.net)}</td><td class="numeric">${money(e.cash+e.card+e.transfer)}</td></tr>`).join('')||'<tr><td colspan="5">No hay operaciones en este filtro.</td></tr>'}</tbody></table></div>`;}
function chart(entries){const buckets=[10,11,12,13,14,15,16,17],vals=buckets.map(h=>entries.filter(e=>+e.hour.split(':')[0]===h).reduce((s,e)=>s+e.net,0)),max=Math.max(100000,...vals),points=vals.map((v,i)=>`${55+i*95},${175-v/max*135}`).join(' ');return `<svg class="chart" viewBox="0 0 770 215" role="img" aria-label="Ventas netas del filtro por hora, en pesos mexicanos"><title>Ventas netas por hora</title>${[0,.5,1].map(v=>`<line x1="55" x2="720" y1="${175-v*135}" y2="${175-v*135}" stroke="#e8eee8"/><text x="46" y="${179-v*135}" text-anchor="end">${Math.round(max*v/100)}</text>`).join('')}<polygon points="55,175 ${points} 720,175" fill="#e9f3ec"/><polyline points="${points}" fill="none" stroke="#338663" stroke-width="2.5"/>${vals.map((v,i)=>`<circle cx="${55+i*95}" cy="${175-v/max*135}" r="3.5" fill="#338663"><title>${buckets[i]}:00 · ${money(v)}</title></circle><text x="${55+i*95}" y="198" text-anchor="middle">${buckets[i]}:00</text>`).join('')}<text x="55" y="18">MXN</text></svg>`;}
function summary(){let data=rows(),sum=k=>data.reduce((s,e)=>s+e[k],0);const metrics=[['Ventas brutas',sum('gross'),'Mercancía reconocida'],['Descuentos',sum('discount'),'Sobre venta de mercancía'],['Ventas netas',sum('net'),'Apartados al liquidar'],['Cobros recibidos',sum('cash')+sum('card')+sum('transfer'),'Dinero recibido en el período'],['Beneficio bruto',sum('net')-sum('cost'),'Mercancía · costo histórico']];return title('Resumen del negocio','Una vista de tus ventas, cobros y pendientes.')+filters()+(!state.online?notice('Sucursal 1 sin conexión simulada. La consulta remota puede estar incompleta; no es una prueba de sincronización real.'):'')+`<div class="cards">${metrics.map((m,i)=>`<div class="card ${i===2?'active':''}"><div class="metric-label">${m[0]}</div><div class="value">${money(m[1])}</div><small>${m[2]}</small></div>`).join('')}</div><div class="panel"><div class="panel-top"><h2>Ventas netas por hora</h2><small>${data.length} movimientos en el filtro</small></div>${chart(data)}</div><div class="bottom-grid"><div class="panel"><div class="panel-top"><h2>Últimos movimientos</h2>${button('goto','Ver todos','data-view="receipts"','link')}</div>${entryTable(data.slice(-4).reverse())}</div><div class="panel"><h2>Para revisar</h2>${alertsContent()}<div class="notice info">Un anticipo aumenta los cobros. La venta del apartado se reconoce al liquidar; entregar no vuelve a sumarla.</div></div></div>`;}
function alertsContent(){const stock=state.products.find(p=>p.id==='p5');return [{id:'stock',active:stock.available<=1,text:'Collar nudo · '+stock.available+' disponibles en Coyoacán',view:'inventory'},{id:'delivery',active:!state.orders.find(o=>o.id==='AP-002').delivered,text:'AP-002 · Liquidado, pendiente de entrega',view:'layaway'},{id:'work',active:!state.orders.find(o=>o.id==='RP-002').delivered,text:'RP-002 · Lista para entregar',view:'repair'}].filter(a=>a.active).map(a=>`<div class="alert-row"><span class="alert-dot"></span><div>${a.text}<br><small>${state.reviewed.includes(a.id)?'Revisada · la causa puede seguir activa':'Revisión pendiente'}</small></div>${button('goto','Abrir',`data-view="${a.view}"`)}${button('review','Revisar',`data-id="${a.id}"`)}</div>`).join('');}
function cartTotal(){return state.cart.reduce((s,x)=>s+state.products.find(p=>p.id===x.id).price*x.qty,0);}
function productGrid(q=''){q=q.toLowerCase();return state.products.filter(p=>(p.name+p.code+p.material).toLowerCase().includes(q)).map(p=>`<button class="product" data-action="add" data-id="${p.id}" aria-label="Agregar ${p.name}"><div class="product-art" aria-hidden="true"><span></span></div><div class="product-name"><strong>${p.name}</strong><small>${p.material} · ${p.available} disponibles</small><b>${money(p.price)}</b></div></button>`).join('')||'<div class="empty">No se encontraron piezas.</div>';}
function sale(){return title('Nueva venta','Inventario compartido de Coyoacán · Importes en MXN')+(!state.session?notice('Abre caja para cobrar o recibir pagos. '+button('goto','Ir a caja','data-view="cash"','link')):'')+(!state.online?notice('Modo sin internet simulado: venta ordinaria permitida; apartados, reparaciones y saldo requieren conexión.'):'')+`<div class="pos-layout"><section><label>Buscar descripción o código<input id="search-products" placeholder="Escanear o buscar una pieza…"></label><div class="products" id="products" style="margin-top:18px">${productGrid()}</div></section><section class="panel"><div class="panel-top"><h2>Venta en curso</h2>${badge('Sucursal 1')}</div>${state.cart.map(x=>{const p=state.products.find(p=>p.id===x.id);return `<div class="cart-row"><div><strong>${p.name}</strong><div class="qty">${button('minus','−',`data-id="${p.id}" aria-label="Quitar una ${p.name}"`)}<span>${x.qty}</span>${button('add','+',`data-id="${p.id}" aria-label="Agregar otra ${p.name}"`)}</div></div><strong>${money(p.price*x.qty)}</strong></div>`;}).join('')||'<div class="empty">Selecciona una pieza para empezar.<br>Las cantidades se revisan contra la disponibilidad conocida.</div>'}<div class="summary-row"><span>Subtotal</span><strong>${money(cartTotal())}</strong></div><div class="summary-row"><span>Descuento · D01 por decidir</span><span>$0.00</span></div><div class="summary-row total"><span>Total</span><span>${money(cartTotal())}</span></div>${button('pay','Continuar al pago',!state.cart.length||!state.session?'disabled':'','primary full')}<p class="tip">Este ejemplo usa precios completos. Modalidad y redondeos de descuento pendientes de confirmar.</p></section></div>`;}
function cash(){const s=state.session;return title('Caja','Una sesión operativa por sucursal · Conteo ciego al cerrar')+`<div class="panel"><div class="cash-header"><h2>${s?'Sesión '+s.id:'Caja cerrada'}</h2>${badge(s?'Abierta':'Sin sesión abierta')}</div><p class="muted">${s?'Sucursal 1 · Operador de ejemplo · Apertura '+money(s.opening):'Las operaciones del resumen pertenecen al historial ficticio. Abre una sesión nueva para tus pruebas.'}</p>${state.mode==='admin'?'<p class="tip">Consulta administrativa. Para abrir, mover efectivo o cerrar, cambia al área Punto de venta.</p>':s?`<div class="actions">${button('cash-move','Entrada, gasto o retiro')}${button('cash-close','Capturar cierre','','primary')}</div><p class="tip">El esperado se oculta durante el conteo. El administrador tiene una consulta separada en el sistema final.</p>`:button('cash-open','Abrir caja','','primary')}</div><div class="panel"><h2>Movimientos de esta demostración</h2>${s?.moves.length?`<div class="table-wrap"><table><thead><tr><th>Concepto</th><th>Motivo / folio</th><th class="numeric">Efectivo</th></tr></thead><tbody>${s.moves.map(m=>`<tr><td>${esc(m.type)}</td><td>${esc(m.reason)}</td><td class="numeric">${money(m.amount)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sin movimientos en una sesión abierta.</p>'}</div>${state.closures.map(c=>`<div class="panel"><h2>Cierre ${c.id}</h2><div class="keyvals"><div><small>Esperado</small><strong>${money(c.expected)}</strong></div><div><small>Contado</small><strong>${money(c.counted)}</strong></div><div><small>Diferencia</small><strong>${money(c.difference)}</strong></div><div><small>Fondo / sobre</small><strong>${money(c.fund)} / ${money(c.envelope)}</strong></div></div></div>`).join('')}`;}
function orders(kind){const data=state.orders.filter(o=>o.kind===kind);return title(kind==='layaway'?'Apartados':'Reparaciones',kind==='layaway'?'Reserva, pagos y entrega como hechos distintos.':'Piezas del cliente · Anticipo y liquidación final · Sin comisión comercial.')+(!state.online?notice('Todas las operaciones de este módulo requieren conexión. Los registros siguientes son solo ejemplos visibles en la maqueta.'):'')+`<div class="toolbar"><span>${data.length} órdenes de ejemplo</span>${state.mode==='pos'?button('new-order',kind==='layaway'?'Nuevo apartado':'Recibir reparación',`data-kind="${kind}" ${!state.online||!state.session?'disabled':''}`,'primary'):badge('Entrega exclusivamente en POS')}</div>${state.mode==='pos'&&!state.session?notice('Abre caja para recibir anticipos o liquidaciones.'):''}<div class="panel table-wrap"><table><thead><tr><th>Folio / cliente</th><th>Estado</th><th class="numeric">Total</th><th class="numeric">Pagado</th><th class="numeric">Pendiente</th><th>Plazo</th></tr></thead><tbody>${data.map(o=>`<tr><td>${button('order',o.id,`data-id="${o.id}"`,'link')}<br><small>${client(o.client)}</small></td><td>${badge(o.delivered?'Entregada':o.paid===o.total?'Liquidada · sin entregar':o.status,o.paid<o.total)}${o.kind==='repair'?'<br><small>'+o.status+'</small>':''}</td><td class="numeric">${money(o.total)}</td><td class="numeric">${money(o.paid)}</td><td class="numeric">${money(o.total-o.paid)}</td><td>${o.due}</td></tr>`).join('')}</tbody></table></div>`;}
function inventory(){return title('Inventario','Tres almacenes · Disponibilidad por estado · Sin separación de stock por sucursal')+`<div class="notice info">Vista de Coyoacán, compartida por ambos locales. Oficina y Santa Rosa se incluyen en el modelo de datos; sus movimientos se construirán en E2.</div><div class="panel table-wrap"><table><thead><tr><th>Pieza / código</th><th>Material</th><th class="numeric">Disponible</th><th class="numeric">Apartada</th><th class="numeric">Dañada</th><th class="numeric">Precio</th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${button('product',p.name,`data-id="${p.id}"`,'link')}<br><small>${p.code}</small></td><td>${p.material}</td><td class="numeric">${p.available}</td><td class="numeric">${p.reserved}</td><td class="numeric">${p.damaged}</td><td class="numeric">${money(p.price)}</td></tr>`).join('')}</tbody></table></div><p class="tip">Altas, Excel, etiquetas, traspasos y bajas están especificados en E0 y requieren construcción E2. No hay conteo físico dentro del alcance.</p>`;}
function clients(){return title('Clientes y saldo a favor','Ejemplos ficticios · Saldos por origen y vigencia')+`<div class="panel table-wrap"><table><thead><tr><th>Cliente</th><th>Teléfono ficticio</th><th class="numeric">Saldo disponible</th><th>Estado</th></tr></thead><tbody>${state.clients.map(c=>`<tr><td>${button('client',c.name,`data-id="${c.id}"`,'link')}</td><td>${c.phone}</td><td class="numeric">${money(c.credit)}</td><td>${badge('Sin vencimiento')}</td></tr>`).join('')}</tbody></table></div>${notice('La aplicación de saldo exige conexión, código del cliente y derecho independiente. Su validación real, emisión y reimpresión protegida se construirán en E4.')}`;}
function sellers(){let data=rows();return title('Vendedores','Atribución comercial distinta del operador y de la comisión')+filters()+`<div class="panel table-wrap"><table><thead><tr><th>Vendedor ficticio</th><th class="numeric">Venta atribuida</th><th>Tratamiento</th></tr></thead><tbody>${['Emma','Lucía','Matanga'].map(s=>`<tr><td>${s}</td><td class="numeric">${money(data.filter(e=>e.seller===s).reduce((n,e)=>n+e.net,0))}</td><td>${s==='Matanga'?'Reparaciones sin comisión':'Porcentaje y captura de cálculo: diseño E7'}</td></tr>`).join('')}</tbody></table></div>`;}
function corrections(){return title('Correcciones de operaciones','Consulta del original y comparación de efectos antes de confirmar')+`<div class="panel"><h2>Ejemplo: corregir medio de pago</h2><p>En septiembre se registró efectivo por $1,000.00; realmente se recibió tarjeta. La corrección se realiza en octubre.</p><div class="keyvals"><div><small>Registro original</small><strong>Efectivo $1,000.00</strong></div><div><small>Vista ajustada</small><strong>Tarjeta $1,000.00</strong></div></div><div class="notice info">Se conserva el cierre original. La corrección explica su diferencia; no genera movimiento físico de efectivo en octubre.</div>${button('correction','Revisar antes y después','','primary')}</div><div class="panel"><h2>Bloqueos que permanecen</h2><p>Orden liquidada: COR-17 impide corregir pagos, importes, piezas o presupuesto, incluso al administrador. Venta con cambios vinculados: no se puede anular por error. Las correcciones reales se construirán en E6.</p></div>`;}
function settings(){return title('Configuración','Acuerdos actuales y decisiones de diseño abiertas')+`<div class="panel"><h2>Reglas confirmadas</h2><div class="table-wrap"><table><tbody><tr><td>Apartados</td><td>40% mínimo · 45 días · cancelación temprana hasta día 7</td></tr><tr><td>Reparaciones</td><td>50% mínimo · sin abonos intermedios · 45 días desde lista</td></tr><tr><td>Cambios</td><td>15 días · mercancía igual o mayor · conexión y permiso</td></tr><tr><td>Saldo a favor</td><td>Sin vencimiento por defecto · uso online con código</td></tr><tr><td>Inventario</td><td>Coyoacán compartido · oficina · Santa Rosa</td></tr></tbody></table></div></div><div class="panel"><h2>Por decidir para E1</h2><p>Modalidad y redondeos del descuento; arquitectura y guardado local; identidad y permisos offline; secuencia de caja; destino de segunda copia; modelo Star, papel y etiquetas.</p><p class="tip">El selector de área de esta maqueta no autentica a nadie. Los perfiles y porcentajes reales aún no están configurados.</p></div>`;}
function render(){const views=state.mode==='admin'?['summary','receipts','cash','inventory','layaway','repair','clients','sellers','alerts','corrections','settings']:['sale','cash','layaway','repair','clients','inventory','receipts','corrections'];if(!views.includes(state.view))state.view=views[0];$('#nav').innerHTML=views.map((v,i)=>`<button data-action="goto" data-view="${v}" ${v===state.view?'aria-current="page"':''}><span class="navmark" aria-hidden="true">${String(i+1).padStart(2,'0')}</span>${names[v]}</button>`).join('');$('#admin').setAttribute('aria-pressed',state.mode==='admin');$('#pos').setAttribute('aria-pressed',state.mode==='pos');$('#online').checked=state.online;$('#connection-label').textContent=state.online?'Con conexión simulada':'Sin internet · simulación';$('#identity').innerHTML=(state.mode==='admin'?'Administración':'Operador de ejemplo')+'<br><small>Modo de demostración</small>';const pages={summary,sale,cash,inventory,clients,sellers,corrections,settings,layaway:()=>orders('layaway'),repair:()=>orders('repair'),receipts:()=>title('Ventas y comprobantes','Abrir un detalle conserva el contexto de consulta.')+filters()+`<div class="panel">${entryTable(rows().slice().reverse())}</div>`,alerts:()=>title('Alertas','Marcar revisada no significa resolver la causa.')+`<div class="panel">${alertsContent()}</div>`};$('#content').innerHTML=pages[state.view]();}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
function modal(title,body){$('#modal').classList.toggle('drawer',state.mode==='admin');$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;if(!$('#modal').open)$('#modal').showModal();}
function form(type,body,label='Confirmar ejemplo',extra=''){return `<form data-form="${type}" ${extra}>${body}<div class="form-error" role="alert"></div><div class="actions"><button class="primary" type="submit">${label}</button>${button('close','Volver')}</div></form>`;}
function field(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra} required></label>`;}
function mustPOS(){if(state.mode!=='pos')throw Error('Esta operación se registra desde el POS.');}
function mustCash(){mustPOS();if(!state.session)throw Error('Abre caja para registrar pagos.');}
function record(data){const e={id:'D-'+(++counter),date:today,hour:'17:15',branch:'Sucursal 1',gross:0,discount:0,cost:0,net:0,cash:0,card:0,transfer:0,seller:'Emma',pending:!state.online,...data};state.entries.push(e);if(state.session&&e.cash)state.session.moves.push({type:e.type,reason:e.id,amount:e.cash});return e;}
function detailOrder(id){const o=state.orders.find(x=>x.id===id);const remaining=o.total-o.paid;modal(o.id+' · '+(o.kind==='layaway'?'Apartado':'Reparación'),`<p><strong>${client(o.client)}</strong><br>${esc(o.description)}</p>${badge(o.status,remaining>0)}<div class="keyvals"><div><small>Total</small><strong>${money(o.total)}</strong></div><div><small>Pendiente</small><strong>${money(remaining)}</strong></div></div>${!remaining?notice('COR-17: economía cerrada desde la liquidación. Se permite completar el trabajo y la entrega.'):''}<ul class="timeline">${o.history.map(h=>`<li>${esc(h)}</li>`).join('')}</ul><div class="actions">${remaining&&state.mode==='pos'?button('order-pay',o.kind==='layaway'?'Registrar abono':'Liquidar',`data-id="${o.id}" ${!state.online||!state.session?'disabled':''}`,'primary'):''}${o.kind==='repair'&&!o.delivered&&o.status!=='Lista para entregar'?button('order-next',o.status==='Recibida'?'Pasar a en reparación':'Marcar lista',`data-id="${o.id}" ${!state.online?'disabled':''}`):''}${!remaining&&!o.delivered?button('deliver','Registrar entrega',`data-id="${o.id}" ${state.mode!=='pos'||!state.online||(o.kind==='repair'&&o.status!=='Lista para entregar')?'disabled':''}`,'primary'):''}</div>${state.mode!=='pos'?'<p class="tip">Pagos y entrega física se recorren en el área Punto de venta.</p>':''}<p class="tip">Cambios de presupuesto, cancelaciones y reimpresión: flujos documentados en E0, se construirán en E5/E6.</p>`);}
const actions={
 goto:b=>{state.view=b.dataset.view;render();}, close:()=>$('#modal').close(),
 add:b=>{const p=state.products.find(x=>x.id===b.dataset.id),item=state.cart.find(x=>x.id===p.id);if((item?.qty||0)+1>p.available)throw Error('No hay más unidades disponibles conocidas.');if(item)item.qty++;else state.cart.push({id:p.id,qty:1});render();},
 minus:b=>{const x=state.cart.find(x=>x.id===b.dataset.id);if(x&&--x.qty===0)state.cart=state.cart.filter(y=>y!==x);render();},
 pay:()=>{mustCash();const t=D.stock(state.cart,state.products);modal('Cobrar venta de ejemplo',form('sale-pay',`<p>Total <strong>${money(t)}</strong> · Tarjeta y transferencia se verifican por fuera del POS.</p><div class="form-grid">${field('cash','Efectivo recibido',(t/100).toFixed(2),'text','inputmode="decimal"')}${field('card','Tarjeta aplicada','0','text','inputmode="decimal"')}${field('transfer','Transferencia aplicada','0','text','inputmode="decimal"')}<label>Vendedor<select name="seller"><option>Emma</option><option>Lucía</option></select></label><label>Tipo tarjeta<select name="cardtype"><option>Débito</option><option>Crédito</option></select></label>${field('bank','Banco ficticio','Banco demo')}${field('last4','Últimos 4 (ficticios)','1234','text','maxlength="4" inputmode="numeric"')}${field('reference','Referencia ficticia','DEMO-001')}</div><p class="tip">Saldo a favor requiere validación de código y permiso; se especifica en E4 y no se cobra en esta maqueta.</p>`,'Registrar venta ficticia'));},
 'cash-open':()=>{mustPOS();modal('Abrir caja',form('cash-open',field('opening','Fondo inicial','500','text','inputmode="decimal"')));},
 'cash-move':()=>{mustCash();modal('Movimiento de efectivo',form('cash-move',`<div class="form-grid"><label>Concepto<select name="kind"><option>Entrada extra</option><option>Gasto</option><option>Retiro</option></select></label>${field('amount','Importe','100','text','inputmode="decimal"')}<label class="wide">Motivo<input name="reason" required maxlength="160"></label></div>`));},
 'cash-close':()=>{mustCash();modal('Conteo ciego',form('cash-close',`<p>Cuenta el efectivo antes de ver el importe esperado.</p><div class="form-grid">${field('counted','Efectivo contado','','text','inputmode="decimal"')}${field('fund','Fondo siguiente','','text','inputmode="decimal"')}${field('envelope','Efectivo en sobre','','text','inputmode="decimal"')}</div>`,'Cerrar y comparar'));},
 order:b=>detailOrder(b.dataset.id),
 'order-pay':b=>{const o=state.orders.find(o=>o.id===b.dataset.id);modal('Pago de '+o.id,form('order-pay',`<p>Pendiente: <strong>${money(o.total-o.paid)}</strong>. El ejemplo registra efectivo recibido exacto.</p>${field('amount',o.kind==='repair'?'Liquidación completa':'Abono',( (o.total-o.paid)/100).toFixed(2),'text','inputmode="decimal"')}`,'Registrar pago ficticio',`data-id="${o.id}"`));},
 'order-next':b=>{D.requireOnline(state.online);const o=state.orders.find(o=>o.id===b.dataset.id);if(o.kind!=='repair'||o.delivered)throw Error('Transición no permitida.');if(o.status==='Recibida'){o.status='En reparación';o.started=true;}else if(o.status==='En reparación'){o.status='Lista para entregar';o.due='2026-11-07';}else throw Error('Transición no permitida.');o.history.push('23/09 · '+o.status);render();detailOrder(o.id);},
 deliver:b=>{const i=state.orders.findIndex(o=>o.id===b.dataset.id),o=state.orders[i];const updated=D.deliver(o,state.online,state.mode);updated.history=[...o.history,'23/09 · Entrega completa en Sucursal 1'];state.orders[i]=updated;if(o.kind==='layaway')o.items.forEach(id=>{const p=state.products.find(p=>p.id===id);p.reserved--;});render();detailOrder(o.id);toast('Entrega ficticia registrada; no suma otra venta ni cobro.');},
 'new-order':b=>{mustCash();D.requireOnline(state.online);const kind=b.dataset.kind;modal(kind==='layaway'?'Nuevo apartado':'Recibir reparación',form('new-order',`<div class="form-grid"><label class="wide">Cliente de ejemplo<select name="client">${state.clients.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label>${kind==='layaway'?`<label class="wide">Piezas (una unidad de cada seleccionada)<select name="products" multiple size="5" required>${state.products.filter(p=>p.available>0).map(p=>`<option value="${p.id}">${p.name} · ${money(p.price)}</option>`).join('')}</select></label><p class="tip wide">Selecciona una o varias piezas. El ejemplo cobra exactamente 40% al crear; entrega el conjunto completo.</p>`:`<label class="wide">Piezas e instrucciones del cliente<textarea name="description" required maxlength="400">Cadena del cliente · Reparar broche</textarea></label>${field('total','Presupuesto acordado','1000','text','inputmode="decimal"')}<p class="tip">El ejemplo cobra exactamente 50%, sin descuentos ni abonos intermedios.</p>`}</div>`,'Registrar anticipo ficticio',`data-kind="${kind}"`));},
 receipt:b=>{const e=state.entries.find(e=>e.id===b.dataset.id);modal('Comprobante '+e.id,`<p>${esc(e.type)} · ${e.branch}<br>${e.date} · ${e.hour}<br>${esc(e.description)}</p><div class="keyvals"><div><small>Venta reconocida</small><strong>${money(e.net)}</strong></div><div><small>Cobro de este movimiento</small><strong>${money(e.cash+e.card+e.transfer)}</strong></div></div><div class="summary-row"><span>Efectivo neto</span><strong>${money(e.cash)}</strong></div><div class="summary-row"><span>Tarjeta</span><strong>${money(e.card)}</strong></div><div class="summary-row"><span>Transferencia</span><strong>${money(e.transfer)}</strong></div>${e.change!==undefined?`<div class="summary-row"><span>Cambio entregado</span><strong>${money(e.change)}</strong></div>`:''}<p class="tip">Vista de ejemplo. No imprime ni constituye comprobante real. La reimpresión física y las copias se validarán con equipos.</p>`);},
 product:b=>{const p=state.products.find(p=>p.id===b.dataset.id);modal(p.name,`<p>${p.code} · ${p.material} · ${p.type}</p><div class="keyvals"><div><small>Disponibles</small><strong>${p.available}</strong></div><div><small>Apartadas / dañadas</small><strong>${p.reserved} / ${p.damaged}</strong></div></div><p>Precio ${money(p.price)}</p>${state.mode==='admin'?'<p>Costo de ejemplo '+money(p.cost)+'</p>':''}<p class="tip">Mismo código para unidades iguales. Cambios de costo no recalculan operaciones anteriores. La protección real de costos se implementará con permisos.</p>`);},
 client:b=>{const c=state.clients.find(c=>c.id===b.dataset.id);modal(c.name,`<p>Teléfono ficticio ${c.phone}</p><div class="keyvals"><div><small>Saldo vigente</small><strong>${money(c.credit)}</strong></div><div><small>Vigencia</small><strong>Sin vencimiento</strong></div></div><p class="tip">El código no se muestra en la ficha ni en el historial. Emitir/reimprimir requiere su flujo protegido.</p><h3>Órdenes vinculadas</h3><div class="menu-list">${state.orders.filter(o=>o.client===c.id).map(o=>button('order',o.id+' · '+esc(o.description),`data-id="${o.id}"`)).join('')}</div>`);},
 review:b=>{if(!state.reviewed.includes(b.dataset.id))state.reviewed.push(b.dataset.id);render();toast('Marcada revisada en el ejemplo. La causa sigue pendiente.');},
 correction:()=>modal('Comparación · ejemplo de corrección',`<p>Operación original: septiembre. Corrección: octubre. Motivo de ejemplo: medio capturado incorrectamente.</p><div class="table-wrap"><table><thead><tr><th>Dato</th><th>Original</th><th>Vista ajustada</th></tr></thead><tbody><tr><td>Efectivo registrado</td><td>$1,000.00</td><td>$0.00</td></tr><tr><td>Tarjeta registrada</td><td>$0.00</td><td>$1,000.00</td></tr><tr><td>Contado/fondo/sobre</td><td>Datos originales</td><td>Se conservan</td></tr><tr><td>Efectivo físico hoy</td><td>$0.00</td><td>$0.00</td></tr></tbody></table></div>${notice('Vista previa únicamente. No registra una corrección. Los permisos, motivo, autorización y efectos reales se construirán en E6.')}`)
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;try{actions[b.dataset.action](b);}catch(err){toast(err.message);}});
document.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();const fd=new FormData(f),val=n=>fd.get(n),cashExpected=()=>state.session.opening+state.session.moves.reduce((s,m)=>s+m.amount,0);try{
 if(f.dataset.form==='sale-pay'){mustCash();const total=D.stock(state.cart,state.products),p=D.payment(total,D.cents(val('cash')),D.cents(val('card')),D.cents(val('transfer')));if(p.card&&(!String(val('bank')).trim()||!/^\d{4}$/.test(val('last4'))))throw Error('Completa banco y cuatro dígitos ficticios.');if(p.transfer&&!String(val('reference')).trim())throw Error('Falta la referencia de transferencia.');let cost=0;const description=state.cart.map(x=>{const a=state.products.find(a=>a.id===x.id);cost+=a.cost*x.qty;return `${x.qty} × ${a.name}`;}).join(', ');state.cart.forEach(x=>state.products.find(p=>p.id===x.id).available-=x.qty);const entry=record({...p,type:'Venta',description,gross:total,net:total,cost,seller:val('seller')});state.cart=[];$('#modal').close();render();actions.receipt({dataset:{id:entry.id}});toast('Venta ficticia registrada. Cambio: '+money(p.change));}
 else if(f.dataset.form==='cash-open'){mustPOS();if(state.session)throw Error('Ya hay una sesión abierta.');state.session={id:'CA-'+(++counter),opening:D.cents(val('opening')),moves:[]};$('#modal').close();render();toast('Caja de ejemplo abierta.');}
 else if(f.dataset.form==='cash-move'){mustCash();const amount=D.cents(val('amount')),reason=String(val('reason')).trim();if(!amount||!reason)throw Error('Se requieren importe positivo y motivo.');state.session.moves.push({type:val('kind'),amount:val('kind')==='Entrada extra'?amount:-amount,reason});$('#modal').close();render();toast('Movimiento ficticio registrado.');}
 else if(f.dataset.form==='cash-close'){mustCash();const c=D.closeCash(cashExpected(),D.cents(val('counted')),D.cents(val('fund')),D.cents(val('envelope')));state.closures.unshift({...c,id:state.session.id});state.session=null;$('#modal').close();render();toast('Cierre ficticio registrado. Diferencia: '+money(c.difference));}
 else if(f.dataset.form==='order-pay'){mustCash();const i=state.orders.findIndex(o=>o.id===f.dataset.id),o=state.orders[i],amount=D.cents(val('amount')),updated=D.orderPayment(o,amount,state.online),liquidated=updated.paid===updated.total;updated.history=[...o.history,`23/09 · ${liquidated?'Liquidación':'Abono'} ${money(amount)}`];if(o.kind==='layaway'&&liquidated)updated.status='Liquidada';state.orders[i]=updated;record({type:liquidated?'Liquidación '+(o.kind==='layaway'?'apartado':'reparación'):'Abono apartado',description:o.id+' · '+o.description,cash:amount,gross:liquidated&&o.kind==='layaway'?o.total:0,net:liquidated&&o.kind==='layaway'?o.total:0,cost:liquidated&&o.kind==='layaway'?o.cost:0,seller:o.seller});render();detailOrder(o.id);toast('Pago ficticio registrado.');}
 else if(f.dataset.form==='new-order'){mustCash();D.requireOnline(state.online);const kind=f.dataset.kind,ids=fd.getAll('products');let total,cost=0,description;if(kind==='layaway'){total=D.stock(ids.map(id=>({id,qty:1})),state.products);description=ids.map(id=>state.products.find(p=>p.id===id).name).join(' + ');cost=ids.reduce((s,id)=>s+state.products.find(p=>p.id===id).cost,0);}else{total=D.cents(val('total'));if(total<=0)throw Error('El presupuesto debe ser positivo.');description=String(val('description')).trim();if(!description)throw Error('Describe las piezas y el trabajo.');}const rate=kind==='layaway'?40:50;if((total*rate)%100!==0)throw Error('Usa un importe de ejemplo cuyo anticipo no requiera redondeo; D01 está pendiente.');const paid=total*rate/100,id=(kind==='layaway'?'AP-':'RP-')+(++counter);const order={id,kind,client:val('client'),items:ids,total,cost,paid,description,date:today,due:kind==='layaway'?'2026-11-07':'Al pasar a lista',seller:kind==='layaway'?'Emma':'Matanga',branch:'Sucursal 1',status:kind==='layaway'?'Pendiente':'Recibida',delivered:false,started:false,history:['23/09 · Alta y anticipo '+money(paid)]};if(kind==='layaway')ids.forEach(id=>{const p=state.products.find(p=>p.id===id);p.available--;p.reserved++;});state.orders.push(order);record({type:kind==='layaway'?'Anticipo apartado':'Anticipo reparación',description:id+' · '+description,cash:paid,seller:order.seller});render();detailOrder(id);toast('Orden ficticia creada. Anticipo: '+money(paid));}
 }catch(err){f.querySelector('.form-error').innerHTML=`<div class="error">${esc(err.message)}</div>`;}});
document.addEventListener('change',e=>{if(e.target.id==='branch'){state.branch=e.target.value;render();}if(e.target.id==='period'){state.period=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='search-products')$('#products').innerHTML=productGrid(e.target.value);});
$('#admin').onclick=()=>{state.mode='admin';state.view='summary';render();};$('#pos').onclick=()=>{state.mode='pos';state.view='sale';render();};$('#online').onchange=e=>{state.online=e.target.checked;if(state.online)state.entries.forEach(e=>e.pending=false);render();toast('Solo cambia el estado simulado de conexión; no envía datos.');};$('#reset').onclick=()=>{if($('#modal').open)$('#modal').close();state=initial();counter=50;render();toast('Demostración restablecida.');};$('#close-modal').onclick=()=>$('#modal').close();render();
